Update schema.json
etalab/schema-indice-durabilite pull request #1
Opened 2024-03-29 14:04 UTC by Anne-charlottebjn

ajouts par Anne-Charlotte

2024-03-29 16:55 UTC, Pierlou requested changes

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Conduites et matériel connexe (incluant l'ensembe des flexibles, filtres et systèmes aquastop)",
petite coquille `ensemble` (sur toutes les occurrences je pense)

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Non démontable"
Il manque une virgule (peut-être encore plus bas)

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Non démontable"
Il manque une virgule

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Non démontable"
Il manque une virgule

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Non démontable"
Il manque une virgule

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "<7",
Ca me semble bizarre que l'on garde toutes les occurrences de `<7`, `8`, `<10`, ... C'est bien voulu ?

2024-03-29 16:55 UTC, Pierlou commented on lave-linge/schema.json
> +                    "Logiciels et micrologiciels, y compris de reinitialisation",
Pas d'accent sur réinitialisation, voulu ?

2024-04-01 15:30 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +                    "Conduites et matériel connexe (incluant l'ensembe des flexibles, filtres et systèmes aquastop)",
la bonne version (extraite des grilles) est celle en vert (ligne 810)

2024-04-01 15:31 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +                    "Logiciels et micrologiciels, y compris de reinitialisation",
oui, mis comme ca dans les grilles

2024-04-03 15:12 UTC, Pierlou requested changes
Beaucoup de lignes en moins 🧹 bravo !

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
Typo `étape` et `nécessaire`

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "lien_documentation pour les professionnels",
Remplacer les espaces par des `_` dans le nom du champ

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "lien_documentation pour les particuliers",
Idem

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
Pas d'accent dans les noms des champs

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_2",
Accent

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
Pour être sûr de comprendre : pour 5 pièces de la liste 2 on note leur nom et le nombre d'étapes nécessaire pour le démontage ? Pour les noms des champs peut-être : `etape_demontage_piece_1_liste_2` et `nom_piece_1_liste_2` ?

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +                    "<11",
Impossible que ce soit 11, 12 ou 14 ?

2024-04-03 15:12 UTC, Pierlou commented on lave-linge/schema.json
> +                    "<11",
Dans la doc il faudra bien expliciter la signification de `<` et `>`, l'un étant strict et pas l'autre de mémoire (`<11` = `11 ou moins` mais `>15` = `plus de 15`)

2024-04-03 15:18 UTC, Pierlou requested changes

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +                    "Lave-linge"
C'est bien `Téléviseur` non ?

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "description": "La note du critère 1.1 Résistance aux contraintes extérieurs du bloc fiabilité : note sur 10 comportant une décimale",
Typo `extérieurs`

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "description": "La note du critère 1.2 ressistance à l'usure fiabilité : note sur 10 comportant une décimale",
Typo `ressistance`

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "lien_documentation pour les professionnels",
remplacer les espaces des `_`

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "lien_documentation pour les particuliers",
Idem

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_démontage_pièce_1",
Pas d'accent (idem pour tous les champs similaires)

2024-04-03 15:18 UTC, Pierlou commented on televiseur/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
typo `étapas`

2024-04-08 07:56 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "lien_documentation pour les professionnels",
ok fait

2024-04-08 07:56 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "lien_documentation pour les particuliers",
ok fait

2024-04-08 07:57 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
je ne comprends pas ce que tu attends et donc comment modifier...

2024-04-08 07:57 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
corrigé

2024-04-08 07:58 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_2",
corrigé

2024-04-08 07:59 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
on ne regarde que les pièces de la liste 2 pour les étapes de démontage, on ne regarde jamais la liste 1 donc je ne vois pas l'interet de le préciser. Il n'y a que cette possibilité dans les infos disponibles

2024-04-08 08:01 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +                    "<11",
il y aura une table de conversion pour remplir le schéma donc le chemin arrière pourra se faire facilement !

2024-04-08 08:02 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +                    "<11",
c'est plus simple ainsi et je ferai une table de conversion. 
j'ai repris le principe du schéma actuel réparabilité en plus

2024-04-08 08:07 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "name": "lien_documentation pour les professionnels",
ok fait

2024-04-08 08:07 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "name": "lien_documentation pour les particuliers",
ok fait

2024-04-08 08:07 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "name": "etape_démontage_pièce_1",
modifié

2024-04-08 08:08 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
typo  ? J'ai remplacé par étapes, faut-il faire autre chose ?

2024-04-08 08:10 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "description": "La note du critère 1.2 ressistance à l'usure fiabilité : note sur 10 comportant une décimale",
faute corrigé

2024-04-08 08:12 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "description": "La note du critère 1.1 Résistance aux contraintes extérieurs du bloc fiabilité : note sur 10 comportant une décimale",
ok

2024-04-08 08:14 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +                    "Lave-linge"
oui c'est modifié erreur de copier collé !

2024-04-08 09:21 UTC, Pierlou commented on lave-linge/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
Il y a des coquilles : `nombre d'étapas` et `necessaire` (manque un "s")

2024-04-08 09:24 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
C'est plus dans un souci d'harmonie, peut-être soit mentionner `liste_2` dans les deux cas, soit dans aucun (et le mettre simplement en description). Là ça m'a amené à me demander s'il s'agissait bien de mêmes pièces à chaque fois

2024-04-08 09:26 UTC, Pierlou commented on televiseur/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
Un "s" à `nécessaire` (et un accent si on veut vraiment être parfaits)

2024-04-08 11:41 UTC, Anne-charlottebjn commented on televiseur/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
ok merci, c'est corrigé partout !

2024-04-08 11:41 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "name": "etape_démontage_pièce_1",
j'ai ajouté ! 
Si on peut enlever des doutes c'est toujours mieux!

2024-04-08 11:41 UTC, Anne-charlottebjn commented on lave-linge/schema.json
> +            "description": "nombre d'étapas de démontage necessaire pour avoir la pièce unitairement la pièce 1 de la liste 2",
corrigé merci !

2024-04-08 12:53 UTC, Pierlou commented on lave-linge/schema.json
> +
Il y a des retours à la ligne superflus dans certains des champs `nom_piece_detachee_...` (ça m'a l'air d'être le dernier point à modifier !)

2024-04-08 13:38 UTC, Pierlou approved these changes
C'est parti 🚀

2024-04-12 07:36 UTC, Pierlou requested changes
Juste ces histoires d'accent et on est bons pour release la première version !

2024-04-12 07:36 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_demontage_pièce_1_liste_2",
Quelques accents sont passés entre les mailles du filet

2024-04-12 07:36 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_demontage_pièce_2_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_demontage_pièce_3_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_demontage_pièce_4_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on lave-linge/schema.json
> +            "name": "etape_demontage_pièce_5_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_demontage_pièce_1_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_demontage_pièce_2_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_demontage_pièce_3_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_demontage_pièce_4_liste_2",
Accent

2024-04-12 07:36 UTC, Pierlou commented on televiseur/schema.json
> +            "name": "etape_demontage_pièce_5_liste_2",
Accent

2024-04-12 07:42 UTC, Pierlou approved these changes

2024-04-12 07:43 UTC, merged